# Generated by Django 3.2.6 on 2021-10-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
