# Generated by Django 3.2.6 on 2021-09-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
